name: video_player_example
description: Demonstrates how to use the video_player plugin.
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter
  video_player_avfoundation:
    # When depending on this package from a real application you should use:
    #   video_player_avfoundation: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../
  video_player_platform_interface: 
    git:
      url: https://github.com/sugith-pi/packages
      path: packages/video_player/video_player_platform_interface
      # ref: da80cda065747ce3715ff2d690f1c9891be8ebfa

dependency_overrides: 
  video_player_platform_interface:
    git:
      url: https://github.com/sugith-pi/packages
      path: packages/video_player/video_player_platform_interface
      # ref: da80cda065747ce3715ff2d690f1c9891be8ebfa

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  path_provider: ^2.0.6
  test: any

flutter:
  uses-material-design: true
  assets:
    - assets/flutter-mark-square-64.png
    - assets/Butterfly-209.mp4
